config/routes.rb
Rails.application.routes.draw do

  root 'members#index'

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :admin, only: [:index, :create, :destroy]
  
  resources :members, except: [:destroy] do
    collection { post :import_new }
    member     { post :tag }
    resources :payments, only: [:new, :create, :edit, :update, :destroy]
    resources :notes, only: [:new, :create, :edit, :update]
    resources :addresses, only: [:new, :create, :edit, :update]  
  end

  resources :addresses, only: [] do
    collection { get :duplicate_address_report }
  end

  resources :payments, only: [:index] do
    collection { post :import_new, :import_update }
  end

  resources :settings, only: [:index, :update]
  

end

app/views/admin/index.html.erb
<p class="alert-box radius alert">This page is for creating and removing administrators who can access this website.  Be very, very careful!</p>
<h1>Adminstrators</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Admin Since:</th>
      <th>Most Recent Sign In:</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.created_at.to_date %></td>
        <td><%= user.current_sign_in_at.to_date unless user.current_sign_in_at.nil? %></td>
        <td><%= link_to 'Destroy', admin_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: "tiny button round alert" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h3>Create A New Admin User:</h3>
<%= form_for(@new_user, url: admin_index_path) do |f| %>
  <% if @new_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@new_user.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
      <% @new_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="small-4 columns field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field small-4 columns">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions button-down-3">
    <%= f.submit class: "button success radius" %>
  </div>
</div>
<% end %>