config/routes.rb
Rails.application.routes.draw do

  root 'members#index'

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :admin, only: [:index, :create, :destroy]
  
  resources :members, except: [:destroy] do
    collection { post :import_new }
    member     { post :tag }
    resources :payments, only: [:new, :create, :edit, :update, :destroy]
    resources :notes, only: [:new, :create, :edit, :update]
    resources :addresses, only: [:new, :create, :edit, :update]  
  end

  resources :addresses, only: [] do
    collection { get :duplicate_address_report }
  end

  resources :payments, only: [:index] do
    collection { post :import_new, :import_update }
  end

  resources :settings, only: [:index, :update]
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Club Membership</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
    <div class="contain-to-grid">
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a href="#"><%= club_name %></a></h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <li class="has-dropdown">
            <a href="#"><%= current_user.email %></a>
            <ul class="dropdown">
              <li><%= link_to 'Update Password', edit_user_registration_path, :class => '' %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => ''  %></li>
            </ul>
          </li>
          <li class="has-dropdown"><%= link_to 'Members', members_path, :class => '' %>
            <ul class="dropdown">
              <li><%= link_to 'All Members', members_path, :class => '' %></li>
              <li><%= link_to 'Create New Member', new_member_path, :class => '' %></li>
              <li><a href="/addresses/duplicate_address_report.csv">Duplicate Address Report</a></li>
            </ul>
          </li>
          <li class=""><%= link_to "Payments", payments_path, :class => 'right-margin'  %></li>
          <li class="has-dropdown"><%= link_to "Site Info", settings_path, :class => ''  %>
            <ul class="dropdown">
              <li><%= link_to "Administrators", admin_index_path, :class => ''  %></li>
              <li><%= link_to "Settings", settings_path, :class => ''  %></li>
            </ul>
          </li>
        </ul>
      </section>
    </nav>
    </div>
    <% end %>

        <% if notice %>
        <div class="row">
          <div class="columns small-12">
            <p class="alert-box success radius"><%= notice %></p>
          </div>
        </div>
        <% end %>
        <% if alert %>
        <div class="row">
          <div class="columns small-12">
              <p class="alert-box alert radius"><%= alert %></p>
          </div>         
        </div>
        <% end %>

    <div class="row">
      <div class="columns small-12">
        <%= yield %>
      </div>
    </div>
    
    <%= javascript_include_tag "application" %>
  </body>
</html>