config/routes.rb
Rails.application.routes.draw do

  root 'members#index'

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :admin, only: [:index, :create, :destroy]
  
  resources :members, except: [:destroy] do
    collection { post :import_new }
    member     { post :tag }
    resources :payments, only: [:new, :create, :edit, :update, :destroy]
    resources :notes, only: [:new, :create, :edit, :update]
    resources :addresses, only: [:new, :create, :edit, :update]  
  end

  resources :addresses, only: [] do
    collection { get :duplicate_address_report }
  end

  resources :payments, only: [:index] do
    collection { post :import_new, :import_update }
  end

  resources :settings, only: [:index, :update]
  

end

app/models/member.rb
class Member < ActiveRecord::Base

  include Member::Export
  include Member::Import

  has_many :payments,   dependent: :destroy
  has_many :notes,      dependent: :destroy
  has_many :addresses,  dependent: :destroy
  has_one  :primary_address, :class_name => "Address"

  delegate :address1, :address2, :city, :state, :zip, :skip_mail, to: :primary_address, allow_nil: true

  validates :first_name, :last_name, :presence => true

  before_save :check_for_duplicate_member

  acts_as_taggable_on :tags

  filterrific(
    default_filter_params: { sorted_by: 'name_asc' },
    available_filters: [
      :search_query,
      :sorted_by,
      :zip_select,
      :last_dues_paid_gte,
      :mail_select,
      :tag_select
    ]
  )

  # default for will_paginate
  self.per_page = 10

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? :desc : :asc
    case sort_option.to_s
    when /^zip_/
      joins{primary_address.outer}.order("zip #{direction} NULLS LAST")
    when /^dues_/
      order("dues_paid #{direction} NULLS LAST")
    when /^name_/
      order(last_name: direction)
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  scope :search_query, lambda { |query|
    return nil  if query.blank?
    # condition query, parse into individual keywords
    q = query.split(" ").map{|x| "%#{x}%"}
    uniq.joins{notes.outer}.where{(first_name.like_any q) | (last_name.like_any q) | (notes.content.like_any q)}
  }

  scope :last_dues_paid_gte, lambda { |ref_date|
    where{dues_paid >= ref_date}
  }

  scope :zip_select, lambda { |zip|
    joins(:primary_address).where{primary_address.zip == zip.to_s}
  }

  scope :mail_select, lambda { |keyword|
    case keyword
    when "skipmail"
      uniq.joins(:addresses).where{(addresses.skip_mail == true)}
    when "greeting"
      uniq.joins(:addresses).where{(addresses.greeting != nil) & (addresses.greeting != "")}
    when "addressee"
      uniq.joins(:addresses).where{(addresses.addressee != nil) & (addresses.addressee != "")}
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  scope :tag_select, lambda {|tag|
    tagged_with(tag)
  }


  def self.options_for_zip_select
    joins(:primary_address).pluck(:zip).uniq.delete_if{|x| x.nil? || x.empty?}.sort.map { |e| [e, e] }
  end

  def self.options_for_sorted_by
    [
      ['Last Name (a-z)', 'name_asc'],
      ['Last Name (z-a)', 'name_desc'],
      ['Dues Last Paid (oldest first)', 'dues_asc'],
      ['Dues Last Paid (newest first)', 'dues_desc'],
      ['Zip Code', 'zip_asc'],
    ]
  end

  def self.options_for_mail_select
    [
      ['Skip Mail', 'skipmail'],
      ['Custom Addressee', 'addressee'],
      ['Custom Greeting', 'greeting'],
    ]
  end

  def self.options_for_tag_select
    ActsAsTaggableOn::Tag.all.map { |tag| [tag.name, tag.name] }
  end

  def full_name
    ([first_name, middle_initial, last_name] - [nil, ""]).join(" ")
  end

  def name_with_title
    ([title, first_name, middle_initial, last_name] - [nil, ""]).join(" ")
  end

  def greeting
    primary_address.try(:calculated_greeting)
  end

  def addressee
    primary_address.try(:calculated_addressee)
  end

  def middle_initial
    return nil if middle_name.nil?
    middle_name[0] + "."
  end

  def self.get_name_by_id(id)
    Member.find(id).full_name
  end

  def check_for_duplicate_member
    first, last = first_name, last_name
    if Member.where{(first_name =~ "%#{first}%") & (last_name =~ "#{last}%")}.count > 1
      errors.add("Another member of same name")
      return false
    else
      return true
    end
  end

end

app/models/member/export.rb
module Member::Export
  extend ActiveSupport::Concern

  module ClassMethods

    def export_mailing_csv
      CSV.generate do |csv|
        columns = ["addressee", "address1", "address2",  "city", "state", "zip", "greeting", "tags"]
        csv << columns
        all.each do |member|
          member.addresses.each do |add|
            next if add.skip_mail == true
            information = add.attributes.values_at("address1", "address2",  "city", "state", "zip")
            information.unshift(add.calculated_addressee)
            information.push(add.calculated_greeting)
            information.push(member.tag_list.join(", "))
            csv << information
          end
        end
      end
    end

    def export_members_csv
      CSV.generate do |csv|
        columns = %w(id first_name middle_name last_name email email2 home_phone
          cell_phone work_phone employer occupation created_at dues_paid addressee
          address1 address2 city state zip greeting)
        csv << columns
        all.each do |member|
          csv << columns.map{|c| member.send(c)}
        end
      end
    end

  end

end

app/models/member/import.rb
module Member::Import
  extend ActiveSupport::Concern

  include Importable

  module ClassMethods

    def import_new(file)
      not_created = []
      check_headers(file, "first_name", "last_name")

      CSV.foreach(file.path, headers: true) do |row|
        member_hash = create_hash(row)
        if hash_has_required_fields?(member_hash, "first_name", "last_name")
          if member_already_exists?(member_hash)
            not_created << "Row #{$.} member already exists: #{member_hash["first_name"]} #{member_hash["last_name"]}."
          else
            create_member(member_hash)
          end
        else
          not_created << "Row #{$.} missing required information: first name or last name."
        end # end hash_has_require_fields?
      end # end CSV.foreach
      return not_created.first(15)
    end # end self.import(file)

    private

    def member_already_exists?(member_hash)
      Member.where{(first_name =~ "%#{member_hash['first_name']}%") & (last_name =~ "#{member_hash['last_name']}%")}.exists?
    end

    def create_member(member_hash)
      member_attributes  =  member_hash.select{|k, v| Member.columns.map(&:name).include?(k)}
      address_attributes =  member_hash.select{|k, v| Address.columns.map(&:name).include?(k)}
      tags               =  member_hash["tags"].split(",").map{|x| x.strip} unless member_hash["tags"].nil?
      note               =  member_hash["note"] unless member_hash["note"].nil?
      new_member                 = Member.create!(member_attributes)
      new_member.primary_address = Address.create!(address_attributes)
      Note.create!(date: Date.today, content: note, member_id: new_member.id) unless member_hash["note"].nil?
      new_member.update(primary_address_id: new_member.primary_address.id)
      new_member.tag_list.add(tags) unless member_hash["tags"].nil?
    end

  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :tag]

  # GET /members
  # GET /members.json
  def index   
    @filterrific = initialize_filterrific(
        Member,
        params[:filterrific],
        :select_options => {
          sorted_by:    Member.options_for_sorted_by,
          zip_select:   Member.options_for_zip_select,
          mail_select:  Member.options_for_mail_select,
          tag_select:   Member.options_for_tag_select
        }) or return  
    @members = @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
      format.csv {
        if params[:csv] == "export_members_csv"
          @members_for_csv = @filterrific.find
          send_data(@members_for_csv.export_members_csv,
            type: 'text/csv', disposition: 'attachment', 
            filename: "members_#{Time.now.to_i}.csv")
        elsif params[:csv] == "export_mailing_csv"
          @members_for_csv = @filterrific.find
          send_data(@members_for_csv.export_mailing_csv,
            type: 'text/csv', disposition: 'attachment', 
            filename: "mailing_#{Time.now.to_i}.csv")
        end
      }
    end

  rescue ActiveRecord::RecordNotFound => e
    # There is an issue with the persisted param_set. Reset it.
    puts "Had to reset filterrific params: #{ e.message }"
    redirect_to(reset_filterrific_url(format: :html)) and return
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)
    @member.tag_list = member_tag_params["tag_list"]
    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    @member.tag_list = member_tag_params["tag_list"] 
    @member.tag_list.add(tag_params)
    @member.attributes = member_params
    respond_to do |format|
      if @member.save
            format.html { redirect_to @member, notice: 'Member was successfully updated.' }
            format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  def tag
    if @member.tag_list.include?(tag_params)
      @member.tag_list.remove(tag_params)
    else
      @member.tag_list.add(tag_params)
    end
    @member.save!  
    redirect_to member_path(@member) 
  end

  def import_new
    response = Member.import_new(params[:file])
    if response.empty?
      redirect_to members_path, notice: "All rows imported and created."
    else 
      redirect_to members_path, alert: "#{response.length} rows rejected: #{response.join(" | ")}"
    end  
  rescue Exception => e
      redirect_to members_path, alert: e 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    def tag_params
      params[:tag]
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :email, :email2, :cell_phone, :home_phone, :work_phone, :employer, :occupation, :title, :dues_paid)
    end

    def member_tag_params
      params.require(:member).permit(:tag_list)
    end
end

app/helpers/members_helper.rb
module MembersHelper

  def combine_with_space(array)
    array.reject!(&:blank?)
    array.join(" ")
  end

  def combine_with_commas(array)
    array.reject!(&:blank?)
    array.join(", ")
  end

  def phone_list
    hash = {"cell" => @member.cell_phone, "home" => @member.home_phone, "work" => @member.work_phone}
    hash.reject! { |k, v| v.blank? }
    hash.map {|k,v| "#{v} (#{k})"}.join(", ")   
  end

  def mail_view(address)
    if address.skip_mail == true
      return "MARKED NO MAIL"
    elsif address.addressee.blank? && address.greeting.blank?
      return "DEFAULT MAILING INFO"
    else
      return "Addressee: #{address.calculated_addressee} | Greeting: #{address.calculated_greeting}"
    end
  end
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="columns small-12 medium-6 large-4 border-right" >
      <h5>Required Member Information</h5>
      <div class="field row">
        <div class="small-4 columns">
          <%= f.label :first_name, class: "right"%><br>
        </div>
        <div class="small-8 columns end">
          <%= f.text_field :first_name, required: true %>
        </div>
      </div>
      <div class="field row">
        <div class="small-4 columns">
          <%= f.label :last_name, class: "right"%><br>
        </div>
        <div class="small-8 columns end">
          <%= f.text_field :last_name, required: true %>
        </div>
      </div>
      <div class="field row">
        <div class="small-4 columns">
          <%= f.label :title, class: "right"%><br>
        </div>
        <div class="small-8 columns end">
          <%= f.text_field :title, placeholder: "Not Required" %>
        </div>
      </div>   
      <div class="field row">
        <div class="small-4 columns">
          <%= f.label :employer, class: "right"%><br>
        </div>
        <div class="small-8 columns end">
          <%= f.text_field :employer, :required => true %>
        </div>
      </div>
      <div class="field row">
        <div class="small-4 columns">
          <%= f.label :occupation, class: "right"%><br>
        </div>
        <div class="small-8 columns end">
          <%= f.text_field :occupation, :required => true %>
        </div>
      </div>        
    </div>

    <div class="columns small-12 medium-6 large-4">
      <h5>Contact Information</h5>
      <div class="field row">
        <div class="small-4 columns">
          <%= f.label :email, class: "right"%><br>
        </div>
        <div class="small-8 columns end">
          <%= f.email_field :email %>
        </div>
      </div>
      <div class="field row">
        <div class="small-4 columns">
          <%= f.label :email2, class: "right"%><br>
        </div>
        <div class="small-8 columns end">
          <%= f.email_field :email2 %>
        </div>
      </div>  
      <div class="field row">
        <div class="small-4 columns">
          <%= f.label :cell_phone, class: "right"%><br>
        </div>
        <div class="small-8 columns end">
          <%= f.telephone_field :cell_phone %>
        </div>
      </div>
      <div class="field row">
        <div class="small-4 columns">
          <%= f.label :home_phone, class: "right"%><br>
        </div>
        <div class="small-8 columns end">
          <%= f.telephone_field :home_phone %>
        </div>
      </div>
      <div class="field row">
        <div class="small-4 columns">
          <%= f.label :work_phone, class: "right"%><br>
        </div>
        <div class="small-8 columns end">
          <%= f.telephone_field :work_phone %>
        </div>
      </div>
    </div>

    <div class="columns small-12 medium-6 large-4">
      <h5>Optional Information</h5>
      <div class="field row">
        <div class="small-4 columns">
          <%= f.label :tag_list, class: "right"%><br>
        </div>
        <div class="small-8 columns end">
          <%= f.text_field :tag_list %>       
          <p>Enter tags separated by commas.</p>
        </div>
      </div> 
      <div class="field row">
        <div class="small-4 columns">
          <%= f.label :dues_paid, class: "right"%><br>
        </div>
        <div class="small-8 columns end">
          <%= f.date_field :dues_paid %>
          <p>Will override the automatic calculation of dues paid date.</p>     
        </div>
      </div> 
      <br><br>   
      <div class="actions row">
        <%= f.submit class: "button radius success right" %>
      </div>
    </div>
    
  
  </div>
  
<% end %>

app/views/members/_list.html.erb
<%# app/views/students/_list.html.erb %>
<div id="filterrific_results">

  <div>
    <%= page_entries_info members %>
  </div>


  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Zip</th>
        <th>Dues Last Paid</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @members.each do |member| %>
        <tr>
          <td><%= member.full_name %></td>
          <td><%= member.address1 %></td>
          <td><%= member.zip %></td>
          <td><%= member.dues_paid %></td>
          <td><%= link_to 'Details and Edit', member_path(member), class: "tiny round info button" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= will_paginate members %>

app/views/members/_member_addresses.html.erb
<caption><%= member.first_name %>'s Addresses</caption>
<table>
  <thead>
    <tr>
      <th width="100">Primary</th>
      <th width="300">Address</th>
      <th width="300">Mailing Info</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% member.addresses.each do |address| %>
      <tr>
        <td><% if address.id == member.primary_address_id %><%= "YES" %><% end %></td>
        <td><%= combine_with_commas([address.address1, address.address2, address.city, address.state, address.zip]) %></td>
        <td><%= mail_view(address) %></td>
        <td><%= link_to 'Edit', edit_member_address_path(member, address), class: "tiny info button round" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/members/_member_notes.html.erb
<caption><%= member.first_name %>'s Notes</caption>
<table class="expand">
  <thead>
    <tr>
      <th width="500">Content</th>
      <th width="200">Date</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% member.notes.each do |note| %>
      <tr>
        <td><%= note.content %></td>
        <td><%= note.date %></td>
        <td><%= link_to 'Edit', edit_member_note_path(member, note), class: "tiny info button round" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/members/_member_payments.html.erb
<caption><%= member.first_name %>'s Payments</caption>
<table>
  <thead>
    <tr>
      <th width="100">Date</th>
      <th width="100">Amount</th>
      <th width="100">Dues?</th>
      <th width="400">Note</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% member.payments.order(date: :desc).each do |payment| %>
      <tr>
        <td><%= payment.date %></td>
        <td>$<%= payment.amount %></td>
        <td><% if payment.dues %>
              <%= "YES" %>
            <% else %>
              <%= "NO" %>
            <% end %>
        </td>
        <td><%= payment.note %></td>
        <td><%= link_to 'Edit', edit_member_payment_path(member, payment), class: "tiny info button round" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

app/views/members/index.html.erb
<h1>Membership</h1>


<div class="row">
<%= form_for_filterrific @filterrific do |f| %>
  <div class = "small-3 columns">
    Search
    <%= f.text_field(:search_query) %>
  </div>
  <div class = "small-3 columns">
    Sorted by
    <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %>
  </div>  
  <div class = "small-3 columns">
    Mail Options Selection
    <%= f.select(
      :mail_select, 
      @filterrific.select_options[:mail_select],
      { include_blank: '- Any -' }) %>
  </div>   
  <div class= "small-3 columns">
    Dues Paid After
    <%= f.date_field(:last_dues_paid_gte) %>
  </div>  
  <div class="small-3 columns">
    Zip Code Selection
    <%= f.select(
      :zip_select,
      @filterrific.select_options[:zip_select],
      { include_blank: '- Any -' }) %>
  </div>
  <div class="small-3 columns">
    Tag Selection
    <%= f.select(
      :tag_select,
      @filterrific.select_options[:tag_select],
      { include_blank: '- Any -' }) %>
  </div>
  <div class="right">
      <%= link_to('Reset filters', reset_filterrific_url, class: "button round tiny info button-down") %>
      <%= link_to 'Export Members CSV', members_path(format: :csv, csv: "export_members_csv"), html_options = {class: "button round tiny success button-down"} %>
      <%= link_to 'Export Mailing CSV', members_path(format: :csv, csv: "export_mailing_csv"), html_options = {class: "button round tiny success button-down"} %>      
  </div>
  <%= render_filterrific_spinner %>
<% end %>
</div>



<%= render(
  partial: 'members/list',
  locals: { members: @members }
) %>

<br>
<hr>
<div class="small-12 columns">
<h3>Import CSV for NEW Members</h3>
<p><strong>Required Headers:</strong> first_name, last_name</p>
<p><strong>Additional Headers:</strong> address1, address2, city, state, zip, email, email2, cell_phone, home_phone, work_phone, employer, occupation, dues_paid, skip_mail, greeting, addressee, middle_name, tags, note</p>
  <%= form_tag import_new_members_path, multipart: true do %>
    <%= file_field_tag :file, required: :true %>
    <%= submit_tag "Import CSV", class: "button small success radius" %>
  <% end %>
</div>

app/views/members/index.js.erb
<% js = escape_javascript(
  render(partial: 'members/list', locals: { members: @members })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

app/views/members/show.html.erb
<h1><%= @member.full_name %></h1>


<div class =  "small-12 columns medium-8">
  <div class="panel">

  <% unless @member.email.blank? && @member.email2.blank? %>
  <p>
    <strong>Email Address(es):</strong>
    <%= combine_with_commas([@member.email, @member.email2])%>
  </p>
  <% end %>

  <% unless @member.cell_phone.blank? && @member.home_phone.blank? && @member.work_phone.blank? %>
  <p>
    <strong>Phone Numbers:</strong>
    <%= phone_list %>
  </p>
  <% end %>

  <% unless @member.employer.blank? && @member.occupation.blank? %>
  <p>
    <strong>Employment:</strong>
    <%= combine_with_commas([@member.occupation, @member.employer]) %>
  </p>
  <% end %>

  <% unless @member.dues_paid.nil? %>
  <p>
    <strong>Dues Last Paid:</strong>
    <%= @member.dues_paid %>
  </p>
  <% end %>  
  </div>

  <% if @member.addresses.present? %>
    <%= render(
      partial: 'members/member_addresses',
      locals: { member: @member }
    ) %>
  <% end %>

  <% if @member.payments.present? %>
    <%= render(
      partial: 'members/member_payments',
      locals: { member: @member }
    ) %>
  <% end %>

  <% if @member.notes.present? %>
    <%= render(
      partial: 'members/member_notes',
      locals: { member: @member }
    ) %>
  <% end %>
</div>

<div class="medium-3 columns right">
<%= link_to 'Edit Member Info', edit_member_path(@member), class: "button info radius expand" %> 
<%= link_to 'Add New Address', new_member_address_path(@member), class: "button info radius expand" %>
<%= link_to 'Add New Payment', new_member_payment_path(@member), class: "button info radius expand" %>
<%= link_to 'Add New Note', new_member_note_path(@member), class: "button info radius expand" %>
</div>
<br>

<div class="small-12 medium-8 columns" id ="tag_add">
  <% ActsAsTaggableOn::Tag.find_each do |tag| %>
    <% if @member.tag_list.include?(tag.name) %>
      <%= link_to tag.name, tag_member_path(@member, tag: tag.name), method: :post, class: "active" %>
    <% else %>
      <%= link_to tag.name, tag_member_path(@member, tag: tag.name), method: :post %>
    <% end %>
  <% end %>
</div>